insert into CURRENCY_EXCHANGE (id, CURRENCY_FROM , CURRENCY_TO, CONVERSION_MULTIPLE , ENVIRONMENT)
values(10001, 'USD', 'INR',65,'');

insert into CURRENCY_EXCHANGE (id, CURRENCY_FROM , CURRENCY_TO, CONVERSION_MULTIPLE , ENVIRONMENT)
values(10002, 'GBP', 'INR',90,'');


insert into CURRENCY_EXCHANGE (id, CURRENCY_FROM , CURRENCY_TO, CONVERSION_MULTIPLE , ENVIRONMENT)
values(10003, 'ASD', 'INR',25,'');
